### ISSUE TITLE
[Feature Request][Question] Record a battle on server to broadcast on client.

### ISSUE THREAD

**Issue by stephanepiriou** [jamro/jsbattle#12] opened 2018-05-11 18:58 UTC
Any Idea of how to record battle server side and be able to broadcast later for replay on client browser ?

The goal would be to get a server where to perform battle to allow leaderboard and avoid cheating. 

Note : Amazing job. The best robojs on github.

**Comment by jamro** [comment] 2018-05-16 09:39
In theory it should be possible to run the simulation on server side in node.js. Rendering and simulation engine layers are separated and it should be possible to use the model only. I have overwritten Math.random by an implementation that is based on a seed number. If you use the same seed for random number generator, you should get the same results of the battle simulation each time.

The tricky part could be isolation of user provided code to make it secured on server side

**Comment by stephanepiriou** [comment] 2018-05-17 21:02
Nice... if that algorithm is made public (we suppose it is the case if it is available on the client) it will be possible to anticipate the outcome of a battle before a fight which is not welcome... 

...but If I privately randomnize on the server the input used in your algorithm (I have yet to see it, but I suppose it's time based)  and send it to the clients, It can solve both the question regarding the record of a battle without taking to much space while preserving its random factor before it is made public and the authenticity of the outcome. 

If that was your idea, it is perfect.

Thank. I will update after i took a look at the algorithm.

Regards.

Stephane.

Sent from Nine
________________________________
De: Krzysztof Jamroz <notifications@github.com>
Envoyé: mercredi 16 mai 2018 11:39 AM
À: jamro/jsbattle
Cc: stephanep; Author 
Objet: Re: [jamro/jsbattle] [Feature Request][Question] Record a battle on server to broadcast on client. (#12)

In theory it should be possible to run the simulation on server side in node.js. Rendering and simulation engine layers are separated and it should be possible to use the model only. I have overwritten Math.random by an implementation that is based on a seed number. If you use the same seed for random number generator, you should get the same results of the battle simulation each time.

The tricky part could be isolation of user provided code to make it secured on server side

**Comment by jamro** [comment] 2018-05-31 14:08
RNG seeding was not working properly but it should be fixed now. 

The seed is provided in `app/webpage/sources/components/screen/battle/Battlefield.js`:

```
onAssetsLoaded() {
    ...
    this.simulation.setRngSeed(Math.random());
    ...
```
replace `Math.random()` by a constant value and you will get the same result of the battle for each time

**Comment by maidenone** [comment] 2019-02-17 14:58
for running client bot code on server take a look at https://www.npmjs.com/package/jailed

i remember that planetwars (aicontest.org) had chroot jails, but they supported atleast 15 different languages, used pipe to/from server / bot and had limited time before timeout between each step. might also have had memory/cpu limits, but might confuse this with other contests. I hosted a copy of the planetwars contest for about 6months, was intended for internal use at our university, but got quite a few global players. this was around 1 year after the official contest ended.

**Comment by jamro** [comment] 2019-03-12 08:21
Implemented as "Battle share link"

**Closed by jamro** 2019-03-12 08:21 UTC
